#!/bin/sh

alias \
	v="$EDITOR" \
	k="kubectl"

alias \
	ll='ls -lSGh' \
	tf="terraform" \
	dc="docker-compose"

alias dot="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"

# Git
gac() {
	if [ -n "$1" ]; then
		git add . && git commit -m "$1"
	else
		echo "No message provided, commit will not process"
	fi
}
