#!/bin/sh

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

unsetopt PROMPT_SP 2>/dev/null

# Default programs
export EDITOR="nvim"
export TERMINAL="alacritty"
export TERMINAL_PROG="alacritty"
export BROWSER="brave"

# Configs
export ZDOTDIR=$HOME/.config/zsh
export PF_INFO="ascii title os kernel host cpu memory uptime pkgs palette"
export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
export GOPATH="$HOME/.local/share/go"
export GOMODCACHE="$HOME/.cache/go/mod"
