#!/bin/sh

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

unsetopt PROMPT_SP 2>/dev/null

# Default programs
export EDITOR="nvim"
export TERMINAL="alacritty"
export TERMINAL_PROG="alacritty"
export BROWSER="brave"

# Configs
# zsh
export ZDOTDIR=$HOME/.config/zsh
export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
export HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/history"
export HISTSIZE=10000000
export SAVEHIST=10000000
# pfetch
export PF_INFO="ascii title os kernel host cpu memory uptime pkgs palette"
# golang
export GOPATH="$HOME/.local/share/go"
export GOMODCACHE="$HOME/.cache/go/mod"
