#!/bin/sh

gac() {
    if [ -n "$1" ]; then
        git add . && git commit -m "$1"
    else
        echo "No message provided, commit will not process"
    fi
}

gcf() {
    local branches branch
    branches=$(git branch --all | grep -v HEAD) &&
        branch=$(echo "$branches" |
            fzf -d $((2 + $(echo "$branches" | wc -l))) +m) &&
        git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}
